2024-09-22 15:17:11,378 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:17:13,056 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:17:16,128 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:17:19,100 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:17:55,860 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:17:58,029 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:18:01,190 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:18:04,113 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:25:03,702 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:25:04,188 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:25:07,028 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:25:10,076 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:26:13,152 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 138, in __init__
    self.update_rate = args[4]
IndexError: list index out of range
2024-09-22 15:33:13,563 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 138, in __init__
    self.update_rate = args[4]
IndexError: list index out of range
2024-09-22 15:35:26,161 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:38:06,165 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:38:09,133 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:38:12,083 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:56:05,721 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:56:08,039 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:56:11,045 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 15:56:14,004 : ERROR : __main__ : Crash!
Traceback (most recent call last):
  File "emulator.py", line 172, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 151, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 67, in __init__
    self.ePort.setText(broker_port)
NameError: name 'broker_port' is not defined
2024-09-22 18:27:37,935 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 225, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 186, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 102, in setup_ui
    self.eSubscribeTopic.setText(self.topic_sub)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-22 18:27:39,050 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 225, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 186, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 102, in setup_ui
    self.eSubscribeTopic.setText(self.topic_sub)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-22 18:27:42,298 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 225, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 186, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 102, in setup_ui
    self.eSubscribeTopic.setText(self.topic_sub)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-22 18:27:45,562 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 225, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 186, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 102, in setup_ui
    self.eSubscribeTopic.setText(self.topic_sub)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-22 18:30:10,066 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 226, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 187, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 102, in setup_ui
    self.eSubscribeTopic.setText(self.topic_sub)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:10:11,284 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 252, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 213, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 96, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:21:53,255 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 264, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 216, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 96, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:24:45,094 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 264, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 216, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 96, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:31:25,996 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 264, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 216, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 96, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:33:31,074 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 267, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 219, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 99, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:41:43,139 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 278, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 222, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 60, in __init__
    self.setup_ui()
  File "emulator.py", line 99, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:44:43,091 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 304, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 248, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 86, in __init__
    self.setup_ui()
  File "emulator.py", line 125, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 12:46:16,413 : ERROR : __main__ : Crash: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
Traceback (most recent call last):
  File "emulator.py", line 279, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 223, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 61, in __init__
    self.setup_ui()
  File "emulator.py", line 100, in setup_ui
    formLayout.addRow("Sub topic", self.eSubscribeTopic)
AttributeError: 'ConnectionDock' object has no attribute 'eSubscribeTopic'
2024-09-24 15:45:54,817 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:45:55,712 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:45:58,676 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:46:01,781 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:47:48,725 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:47:50,792 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:47:53,776 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:48:29,330 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:48:31,748 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:48:34,852 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:49:09,088 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
2024-09-24 15:49:11,685 : ERROR : __main__ : Crash: MC cannot be converted to PyQt5.QtCore.QObject in this context
Traceback (most recent call last):
  File "emulator.py", line 283, in <module>
    mainwin = MainWindow(argv)
  File "emulator.py", line 227, in __init__
    self.connectionDock = ConnectionDock(self.mc, self.name, self.topic_sub, self.topic_pub)
  File "emulator.py", line 65, in __init__
    self.mc.message_received.connect(self.update_btn_state)
TypeError: MC cannot be converted to PyQt5.QtCore.QObject in this context
